volumes:
  mongo-data:
    external: true

services:
  trip_service:
    build:
      context: trip_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./trip_service:/app
    environment:
      DATABASE_URL: mongodb://root:password@mongo
      DATABASE_NAME: mongo-data
      WAIT_HOSTS: mongo:27017
      SIGNING_KEY: ${SIGNING_KEY}
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60

  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: north
      MONGO_INITDB_ROOT_PASSWORD: star


  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      # REACT_APP_TRIP_SERVICE_API_HOST: http://www.google.com
