volumes:
  mongo-data:
    external: true

services:
  trip-service:
    build:
      context: trip-service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./trip-service:/app
    environment:
      DATABASE_URL: mongodb://root:kj4hgfmf058fggjdlolgfj@mongo/admin
      DATABASE_NAME: mongo-data
      WAIT_HOSTS: mongo:27017
      SIGNING_KEY: ${SIGNING_KEY}
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60

  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kj4hgfmf058fggjdlolgfj

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: kj4hgfmf058fggjdlolgfj
      ME_CONFIG_MONGODB_URL: mongodb://root:kj4hgfmf058fggjdlolgfj@mongo:27017/
    restart: always

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_ACCOUNTS_HOST: http://localhost:8000
      REACT_APP_GOOGLE_API_KEY: ${GOOGLE_API_KEY}
